/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hixxecrodoqpnxarfzdd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpeHhlY3JvZG9xcG54YXJmemRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxMDMyMDgsImV4cCI6MjA5MjY3OTIwOH0.LiWCjiF2ng7akGq10kp8L_-fu7H-RtkI_5R14tBUDOk"